spring.application.name=plan-service

spring.datasource.url=jdbc:postgresql://localhost:5432/dayx
spring.datasource.username=dayx
spring.datasource.password=dayx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata